import Vue from 'vue'
import {
  Button,
  Search,
  Swipe,
  SwipeItem,
  Image,
  Lazyload,
  Grid,
  GridItem,
  Cell,
  CellGroup,
  Card,
  Tabbar,
  TabbarItem,
  TreeSelect,
  Tab,
  Tabs,
  Pagination,
  icon,
  NavBar,
  Sku,
  GoodsAction,
  GoodsActionIcon,
  GoodsActionButton,
  Toast,
  Checkbox,
  CheckboxGroup,
  SubmitBar
} from 'vant'

Vue.use(SubmitBar)
Vue.use(Checkbox)
Vue.use(CheckboxGroup)
Vue.use(Card)
Vue.use(GoodsActionButton)
Vue.use(GoodsAction)
Vue.use(GoodsActionIcon)
Vue.use(Sku)
Vue.use(NavBar)
Vue.use(icon)
Vue.use(Pagination)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(Tabbar)
Vue.use(TreeSelect)
Vue.use(TabbarItem)
Vue.use(Card)
Vue.use(Cell)
Vue.use(CellGroup)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Lazyload)
Vue.use(Image)
Vue.use(Swipe)
Vue.use(SwipeItem)
Vue.use(Button)
Vue.use(Search)
Vue.prototype.$toast = Toast
